#!/usr/bin/env python3
"""Handwriting SVG Generator — GUI application.

Creates A4-sized SVG files with realistic single-stroke handwriting
generated by a neural network, suitable for pen plotters.
"""

import os
import sys
import threading
import tkinter as tk
from tkinter import ttk, filedialog, messagebox

from engine import HandwritingRenderer, generate_svg, generate_lac, generate_pdf

PREVIEW_PADDING = 20


class HandwritingApp:
    def __init__(self, root):
        self.root = root
        self.root.title('Handwriting SVG Generator')
        self.root.geometry('1100x750')
        self.root.minsize(900, 600)

        self._svg_paths = []
        self._polylines = []
        self._page_w = 210.0
        self._page_h = 297.0
        self._rendering = False
        self._model_ready = False
        self._zoom = None  # None means auto fit-to-width

        self._build_ui()
        self._preload_model()

    def _build_ui(self):
        paned = ttk.PanedWindow(self.root, orient=tk.HORIZONTAL)
        paned.pack(fill=tk.BOTH, expand=True, padx=6, pady=6)

        # ── Left panel: controls ──
        left = ttk.Frame(paned, width=320)
        paned.add(left, weight=0)

        ttk.Label(left, text='Text:', font=('', 11, 'bold')).pack(anchor='w', padx=8, pady=(8, 2))
        self.text_input = tk.Text(left, height=10, width=36, wrap='word', font=('', 11))
        self.text_input.pack(fill=tk.X, padx=8, pady=(0, 6))
        self.text_input.insert('1.0',
            'The quick brown fox jumps over the lazy dog. '
            'Pack my box with five dozen liquor jugs!\n\n'
            'Handwriting synthesis using a recurrent neural network.'
        )

        ttk.Separator(left, orient='horizontal').pack(fill=tk.X, padx=8, pady=4)

        settings = ttk.LabelFrame(left, text='Settings', padding=8)
        settings.pack(fill=tk.X, padx=8, pady=4)

        # Style (0-12)
        style_frame = ttk.Frame(settings)
        style_frame.pack(fill=tk.X, pady=2)
        ttk.Label(style_frame, text='Handwriting style:').pack(side=tk.LEFT)
        self.style_var = tk.IntVar(value=1)
        style_spin = ttk.Spinbox(style_frame, from_=0, to=12, textvariable=self.style_var, width=4)
        style_spin.pack(side=tk.RIGHT)

        # Bias (neatness)
        self.bias_var = tk.DoubleVar(value=0.80)
        self._add_slider(settings, 'Neatness (bias):', self.bias_var, 0.0, 1.5, 0.05)

        # Scale
        self.scale_var = tk.DoubleVar(value=1.0)
        self._add_slider(settings, 'Scale:', self.scale_var, 0.5, 2.0, 0.1)

        # Line spacing
        self.line_spacing_var = tk.DoubleVar(value=1.0)
        self._add_slider(settings, 'Line spacing:', self.line_spacing_var, 0.6, 2.0, 0.1)

        # Chars per line
        cpl_frame = ttk.Frame(settings)
        cpl_frame.pack(fill=tk.X, pady=2)
        ttk.Label(cpl_frame, text='Max chars/line:').pack(side=tk.LEFT)
        self.max_chars_var = tk.IntVar(value=60)
        cpl_spin = ttk.Spinbox(cpl_frame, from_=20, to=75, textvariable=self.max_chars_var, width=4)
        cpl_spin.pack(side=tk.RIGHT)

        # Stroke width
        self.stroke_width_var = tk.DoubleVar(value=0.25)
        self._add_slider(settings, 'Stroke width (mm):', self.stroke_width_var, 0.1, 1.5, 0.05)

        # Color
        color_frame = ttk.Frame(settings)
        color_frame.pack(fill=tk.X, pady=2)
        ttk.Label(color_frame, text='Ink color:').pack(side=tk.LEFT)
        self.color_var = tk.StringVar(value='#1a1a2e')
        ttk.Entry(color_frame, textvariable=self.color_var, width=10).pack(side=tk.RIGHT)

        # Buttons
        btn_frame = ttk.Frame(left)
        btn_frame.pack(fill=tk.X, padx=8, pady=8)

        self.generate_btn = ttk.Button(btn_frame, text='Generate Handwriting',
                                       command=self._generate, state='disabled')
        self.generate_btn.pack(fill=tk.X, pady=2)
        ttk.Button(btn_frame, text='Export SVG...',
                   command=self._export_svg).pack(fill=tk.X, pady=2)
        ttk.Button(btn_frame, text='Export PDF...',
                   command=self._export_pdf).pack(fill=tk.X, pady=2)
        ttk.Button(btn_frame, text='Export LAC (Bambu Suite)...',
                   command=self._export_lac).pack(fill=tk.X, pady=2)

        # Status
        self.status_var = tk.StringVar(value='Loading neural network model...')
        ttk.Label(left, textvariable=self.status_var, foreground='gray').pack(
            anchor='w', padx=8, pady=(0, 8))

        # ── Right panel: preview ──
        right = ttk.Frame(paned)
        paned.add(right, weight=1)

        header = ttk.Frame(right)
        header.pack(fill=tk.X, padx=8, pady=(8, 2))
        ttk.Label(header, text='Preview (A4)', font=('', 11, 'bold')).pack(side=tk.LEFT)
        self._zoom_label = ttk.Label(header, text='', foreground='gray')
        self._zoom_label.pack(side=tk.RIGHT)
        ttk.Button(header, text='Fit', width=4,
                   command=self._zoom_fit).pack(side=tk.RIGHT, padx=(0, 4))

        canvas_frame = ttk.Frame(right)
        canvas_frame.pack(fill=tk.BOTH, expand=True, padx=8, pady=(0, 8))

        self.canvas = tk.Canvas(canvas_frame, bg='#e0e0e0', highlightthickness=0)
        self._vscroll = ttk.Scrollbar(canvas_frame, orient=tk.VERTICAL,
                                      command=self.canvas.yview)
        self._hscroll = ttk.Scrollbar(canvas_frame, orient=tk.HORIZONTAL,
                                      command=self.canvas.xview)
        self.canvas.configure(xscrollcommand=self._hscroll.set,
                              yscrollcommand=self._vscroll.set)

        self.canvas.grid(row=0, column=0, sticky='nsew')
        self._vscroll.grid(row=0, column=1, sticky='ns')
        self._hscroll.grid(row=1, column=0, sticky='ew')
        canvas_frame.grid_rowconfigure(0, weight=1)
        canvas_frame.grid_columnconfigure(0, weight=1)

        self.canvas.bind('<Configure>', self._on_canvas_resize)
        # Scroll-wheel zoom
        self.canvas.bind('<MouseWheel>', self._on_scroll_zoom)           # macOS / Windows
        self.canvas.bind('<Button-4>', self._on_scroll_zoom)             # Linux scroll up
        self.canvas.bind('<Button-5>', self._on_scroll_zoom)             # Linux scroll down
        # Click-drag panning
        self.canvas.bind('<ButtonPress-1>', self._on_pan_start)
        self.canvas.bind('<B1-Motion>', self._on_pan_move)

    def _add_slider(self, parent, label, var, from_, to, resolution):
        frame = ttk.Frame(parent)
        frame.pack(fill=tk.X, pady=2)
        ttk.Label(frame, text=label).pack(side=tk.LEFT)
        value_label = ttk.Label(frame, text=f'{var.get():.2f}', width=6)
        value_label.pack(side=tk.RIGHT)
        slider = ttk.Scale(frame, from_=from_, to=to, variable=var, orient=tk.HORIZONTAL,
                           command=lambda v, vl=value_label, va=var: vl.config(text=f'{va.get():.2f}'))
        slider.pack(side=tk.RIGHT, fill=tk.X, expand=True, padx=(6, 6))

    def _preload_model(self):
        """Load the neural network in a background thread."""
        def load():
            from engine import HandwritingModel
            HandwritingModel.get()
            self._model_ready = True
            self.root.after(0, self._on_model_ready)
        threading.Thread(target=load, daemon=True).start()

    def _on_model_ready(self):
        self.status_var.set('Model loaded. Ready to generate.')
        self.generate_btn.config(state='normal')
        self._draw_empty_page()

    def _get_renderer(self):
        return HandwritingRenderer(
            style=self.style_var.get(),
            bias=self.bias_var.get(),
            stroke_width=self.stroke_width_var.get(),
            color=self.color_var.get(),
            scale=self.scale_var.get(),
            line_spacing=self.line_spacing_var.get(),
            max_chars_per_line=self.max_chars_var.get(),
        )

    def _generate(self):
        if self._rendering:
            return
        self._rendering = True
        self.generate_btn.config(state='disabled')
        self.status_var.set('Generating handwriting...')
        self.root.update_idletasks()

        def do_render():
            text = self.text_input.get('1.0', 'end-1c')
            renderer = self._get_renderer()
            try:
                paths, polys, pw, ph = renderer.render(text)
                self.root.after(0, lambda: self._on_render_done(
                    paths, polys, pw, ph, renderer.color, renderer.stroke_width))
            except Exception as e:
                self.root.after(0, lambda: self._on_render_error(str(e)))

        threading.Thread(target=do_render, daemon=True).start()

    def _on_render_done(self, paths, polys, pw, ph, color, stroke_width):
        self._svg_paths = paths
        self._polylines = polys
        self._page_w = pw
        self._page_h = ph
        self._render_color = color
        self._render_stroke_width = stroke_width
        self._rendering = False
        self.generate_btn.config(state='normal')
        self.status_var.set(f'Generated {len(paths)} stroke(s).')
        self._draw_preview()

    def _on_render_error(self, msg):
        self._rendering = False
        self.generate_btn.config(state='normal')
        self.status_var.set(f'Error: {msg}')
        messagebox.showerror('Render Error', msg)

    def _get_preview_scale(self):
        """Return the current zoom scale (pixels per mm)."""
        cw = self.canvas.winfo_width()
        if cw < 10:
            return 1.0
        pw = self._page_w
        if self._zoom is None:
            # Fit to width by default
            return (cw - 2 * PREVIEW_PADDING) / pw
        return self._zoom

    def _on_canvas_resize(self, event=None):
        if self._zoom is None:
            # Re-fit when in auto mode
            pass
        if self._polylines:
            self._draw_preview()
        elif self._model_ready:
            self._draw_empty_page()

    def _on_scroll_zoom(self, event):
        # Determine scroll direction
        if event.num == 4:
            delta = 1
        elif event.num == 5:
            delta = -1
        else:
            delta = event.delta

        factor = 1.15 if delta > 0 else 1 / 1.15
        old_scale = self._get_preview_scale()
        new_scale = old_scale * factor
        # Clamp to reasonable range (0.5x to 20x pixels per mm)
        new_scale = max(0.5, min(20.0, new_scale))
        self._zoom = new_scale
        self._draw_preview() if self._polylines else self._draw_empty_page()

    def _zoom_fit(self):
        self._zoom = None
        self._draw_preview() if self._polylines else self._draw_empty_page()

    def _on_pan_start(self, event):
        self.canvas.scan_mark(event.x, event.y)

    def _on_pan_move(self, event):
        self.canvas.scan_dragto(event.x, event.y, gain=1)

    def _draw_page(self, scale, pw, ph):
        """Draw the page background, shadow, and margins at the given scale."""
        ox = PREVIEW_PADDING
        oy = PREVIEW_PADDING

        self.canvas.create_rectangle(ox + 3, oy + 3, ox + pw*scale + 3, oy + ph*scale + 3,
                                     fill='#aaa', outline='')
        self.canvas.create_rectangle(ox, oy, ox + pw*scale, oy + ph*scale,
                                     fill='white', outline='#999')
        return ox, oy

    def _draw_empty_page(self):
        """Draw an empty A4 page on the canvas."""
        self.canvas.delete('all')
        pw, ph = 210.0, 297.0
        scale = self._get_preview_scale()

        total_w = pw * scale + 2 * PREVIEW_PADDING
        total_h = ph * scale + 2 * PREVIEW_PADDING
        self.canvas.configure(scrollregion=(0, 0, total_w, total_h))

        self._draw_page(scale, pw, ph)
        self._zoom_label.config(text=f'{scale / ((self.canvas.winfo_width() - 2 * PREVIEW_PADDING) / pw) * 100:.0f}%')

    def _draw_preview(self):
        if not hasattr(self, '_polylines'):
            return

        self.canvas.delete('all')
        pw, ph = self._page_w, self._page_h
        scale = self._get_preview_scale()

        total_w = pw * scale + 2 * PREVIEW_PADDING
        total_h = ph * scale + 2 * PREVIEW_PADDING
        self.canvas.configure(scrollregion=(0, 0, total_w, total_h))

        ox, oy = self._draw_page(scale, pw, ph)

        # Margin guides
        renderer = self._get_renderer()
        m = renderer.margins
        mx1 = ox + m['left'] * scale
        my1 = oy + m['top'] * scale
        mx2 = ox + (pw - m['right']) * scale
        my2 = oy + (ph - m['bottom']) * scale
        self.canvas.create_rectangle(mx1, my1, mx2, my2, outline='#ddd', dash=(4, 4))

        # Draw strokes
        color = getattr(self, '_render_color', '#1a1a2e')
        sw = max(1, getattr(self, '_render_stroke_width', 0.4) * scale)

        for polyline in self._polylines:
            if len(polyline) < 2:
                continue
            coords = []
            for x, y in polyline:
                coords.extend([ox + x * scale, oy + y * scale])
            self.canvas.create_line(*coords, fill=color, width=sw,
                                    smooth=False, capstyle='round', joinstyle='round')

        self._zoom_label.config(text=f'{scale / ((self.canvas.winfo_width() - 2 * PREVIEW_PADDING) / pw) * 100:.0f}%')

    def _export_svg(self):
        if not self._svg_paths:
            messagebox.showinfo('No Data', 'Generate handwriting first.')
            return

        svg_content = generate_svg(self._svg_paths,
                                   getattr(self, '_render_color', '#1a1a2e'),
                                   getattr(self, '_render_stroke_width', 0.4))

        path = filedialog.asksaveasfilename(
            title='Save SVG',
            defaultextension='.svg',
            filetypes=[('SVG files', '*.svg'), ('All files', '*.*')],
        )
        if path:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(svg_content)
            messagebox.showinfo('Exported', f'SVG saved to:\n{path}')


    def _export_pdf(self):
        if not self._svg_paths:
            messagebox.showinfo('No Data', 'Generate handwriting first.')
            return

        path = filedialog.asksaveasfilename(
            title='Save PDF',
            defaultextension='.pdf',
            filetypes=[('PDF files', '*.pdf'), ('All files', '*.*')],
        )
        if path:
            try:
                generate_pdf(self._svg_paths, path,
                             getattr(self, '_render_color', '#1a1a2e'),
                             getattr(self, '_render_stroke_width', 0.4))
                messagebox.showinfo('Exported', f'PDF saved to:\n{path}')
            except Exception as e:
                messagebox.showerror('Export Error', str(e))

    def _export_lac(self):
        if not self._svg_paths:
            messagebox.showinfo('No Data', 'Generate handwriting first.')
            return

        path = filedialog.asksaveasfilename(
            title='Save LAC (Bambu Suite)',
            defaultextension='.lac',
            filetypes=[('Bambu Suite files', '*.lac'), ('All files', '*.*')],
        )
        if path:
            try:
                generate_lac(self._svg_paths, path)
                messagebox.showinfo('Exported', f'LAC saved to:\n{path}')
            except Exception as e:
                messagebox.showerror('Export Error', str(e))


def main():
    root = tk.Tk()

    # Enable Retina / HiDPI rendering on macOS
    if sys.platform == 'darwin':
        dpi_scale = root.winfo_fpixels('1i') / 72.0
        root.tk.call('tk', 'scaling', dpi_scale)

    HandwritingApp(root)
    root.mainloop()


if __name__ == '__main__':
    main()
